/* Banco oficial DATAPREV - ATI Desenvolvimento de Software - FGV.
   Caderno TIPO 4 (AZUL), prova aplicada em 17/11/2024.

   Enunciados e alternativas transcritos LITERALMENTE do caderno. Ao editar,
   mantenha a fidelidade ao original: não resuma, não reescreva, não corrija a
   redação da banca. O que a FGV cobra está justamente nos qualificadores
   ("apenas", "exclusivamente", "sempre") e no comprimento das alternativas.

   Convenções:
   - **trecho** marca o que o caderno traz sublinhado ou em negrito.
   - `passage` guarda o texto de apoio (texto-base, versos, frase de
     referência, código) tal como impresso.
   - O gabarito de cada questão é conferido no fim do arquivo contra o
     gabarito oficial do Tipo 4. */
const q = (
  id,
  subject,
  subtopic,
  statement,
  options,
  correctAnswer,
  explanation,
  area,
  passage,
) => ({
  id,
  subject,
  // Área temática. O id é o mesmo da seção correspondente em theory.js, então
  // o botão "Teoria" sempre cai no assunto certo e a aba Foco agrupa por aqui.
  area,
  theoryRef: area,
  subtopic,
  passage,
  statement,
  options,
  correctAnswer,
  explanation: `Gabarito ${String.fromCharCode(65 + correctAnswer)}. ${explanation}`,
});
const P = "Língua Portuguesa",
  I = "Língua Inglesa",
  R = "Raciocínio Lógico-Matemático",
  A = "Atualidades",
  L = "Legislação & Proteção de Dados",
  T = "Conhecimentos Específicos de TI";

// --- TEXTOS-BASE DO CADERNO (compartilhados por vários itens) ---

// "Use the following TEXT to answer the next six questions." (questões 13 a 18)
const TXT_CONSULTING = `Technology Consultant Fast Track: How to Get Your Dream Job in IT Consulting (IT Consulting Career Guide).
(English Edition) eBook Kindle only.

Jumpstart your IT job search and land your dream job while your peers are still "freshening up" their resumes!

Proven techniques to land your dream job as a high-paid IT consultant—you don't want to miss these, if you are serious about a career in IT!

Answers to IT consulting career questions most people fail to ask; actionable advice and real-life stories from seasoned IT consultants!

As a fresh graduate looking for your first job, if you just do what almost everybody else is doing…you will land a hellhole job with lousy pay, long hours, nasty coworkers, and exclusively clients from hell (because you thought it was your only option to go forward in your career). If you are serious and can apply simple instructions, this book can help you become a high-paid IT consultant in your dream job by the end of the month!

If you already have your first or second job in the field of IT, or even have 20 years of work experience, this book will tell you what a great option a career in IT consulting can be. With this book, you can find out why your current job is not satisfying your career aspirations **and** turn your career around for the better!

Containing lessons from a PhD with 12 years of experience and 15,000 billable hours from Accenture and Coala, this is the book movers and shakers in the IT industry are talking about. Recommended by university professors, last-year students, as well as seasoned consultants. Even my mom says you have to read this book, or you have to answer to **her**!

By reading this book, you will learn:
What your college professor didn't tell you about the consulting business.
The Pro's and Con's of a career in technology consulting.
What other options do you have besides working for one of the global consulting giants such as Accenture, Capgemini, Deloitte, Ernst & Young (EY), KPMG, or PricewaterhouseCoopers (PwC).
The must-have characteristics to succeed in IT consulting (if you don't have these, you are doomed to FAIL!).
How to find your money-making niche in IT consulting.
How to get the best results with the least possible effort in your job search.
Best ways to prepare for the job interview in 30 minutes or less.
What questions to ask in the interview to avoid nasty surprises when you are selected.

Hear what others are saying:
★★★★★ "The book gives a strong and realistic description of IT consultancy. **Thus**, every IT student should read the book before they graduate as it will increase their probability of landing a dream job." Samuli Pekkola, Professor, PhD, in Information Systems Sciences, Tampere University
★★★★★ "The book gives insight into technology consulting and provides great tips for job search. I believe it will be very valuable when I start looking for a position in IT. The section on how to stand out as a candidate for a job was an eyeopener." Saku Sikiö, Information Systems Student, University of Jyväskylä
★★★★★ "This is the book I would have needed on the verge of graduation!" Teijo Kelander, MSc, Quality Consultant and Agile Coach
★★★★★ "If you are serious about IT consultancy as a profession, this book is a must-read! As a recruiter, I would prefer that applicants would better understand what this is all about." Petteri Laamanen, MSc, CEO & Founder, Coala
★★★★★ "This book gave me valuable insights into the IT consultant's working life, making it easier to consider the pros and cons in relation to my own values and goals." Janita Kingelin, MSc, Marketing Manager, SoulCore
★ If you want great results in your technology consultant job search, get this book right now!

https://www.amazon.com.br/Technology-Consultant-Fast-Track-Consulting-ebook/dp/B0918JB48D`;

// "Use the following TEXT to answer the next four questions." (questões 19 a 22)
const TXT_APPECO = `Research-Article
How to be a successful app developer: lessons from the simulation of an app ecosystem
Soo Ling Lim, Peter J. Bentley

Abstract
App developers are constantly competing against each other to win more downloads for their apps. With hundreds of thousands of apps in these online stores, what strategy **should** a developer use to be successful? **Should** they innovate, make many similar apps, optimize their own apps or just copy the apps of others? Looking more deeply, how does a complex app ecosystem perform when developers choose to use different strategies? This paper investigates these questions using AppEco, the first Artificial Life model of mobile application ecosystems. In AppEco, developer agents build and upload apps to the app store; user agents **browse** the store and download the apps. A distinguishing feature of AppEco is the explicit modelling of apps as artefacts. In this work we use AppEco to simulate Apple's iOS app ecosystem and investigate common developer strategies, evaluating them in terms of downloads received, app diversity, and adoption **rate**.

https://dl.acm.org/doi/10.1145/2384697.2384698`;

// "Use the following TEXT to answer the next two questions." (questões 23 e 24)
const TXT_PRINTER = `It's not often we write about printers here on the Giz, but Brother's new MPrint MW-260 gets honorable mention for being the world's thinnest printer. **It** can print up to 20 pages per minute from any PC, Pocket PC, or Windows Mobile handheld. Best of all, it also prints over Bluetooth (in addition to your standard USB). No word on pricing or availability, but this is **a 1-pound printer** we wouldn't mind adding to our travel bag. It's worth buying!

Louis Ramirez
http://www.gizmodo.com/`;

const questionsData = [
  q(
    1,
    P,
    "Concordância nominal",
    "Assinale a opção correta em relação à concordância nominal.",
    [
      "A candidata parece meia confusa.",
      "É proibido a entrada de visitantes nessa área.",
      "A diretora achou um e outro funcionário cumpridor.",
      "A entrada para o teatro, atualmente, está muito caro.",
      "As certidões estão anexas ao processo.",
    ],
    4,
    "Anexas é adjetivo e concorda com certidões. Nas demais: meia deveria ser meio (advérbio); É proibida a entrada, por haver o determinante a; um e outro funcionário cumpridores, com adjetivo no plural; e a entrada está muito cara, concordando com o sujeito.",
    "portugues-normativa",
  ),
  q(
    2,
    P,
    "Relações semânticas",
    "Assinale a opção que indica corretamente a noção semântica expressa pelo elemento destacado em: “A moça recostara-se em uma cadeira de balanço no claro de uma janela, **de modo que** seu gracioso vulto imergia-se na plena luz”.",
    ["Consequência.", "Causa.", "Finalidade.", "Tempo.", "Proporcionalidade."],
    0,
    "De modo que introduz o resultado efetivo da posição em que a moça se recostou: valor consecutivo. Só seria final se equivalesse a “para que”, com verbo no subjuntivo.",
    "portugues-sintaxe",
  ),
  q(
    3,
    P,
    "Interpretação",
    "Assinale a opção correta sobre o sentido da frase em destaque.",
    [
      "É impossível ser feliz e viver.",
      "Viver pressupõe felicidade.",
      "Há uma relação paradoxal entre felicidade e vida.",
      "É preciso esquecer da felicidade para obtê-la.",
      "Descreve-se o caráter efêmero da felicidade.",
    ],
    2,
    "Dizer que a felicidade é oposta à vida e, ao mesmo tempo, que se está nela é uma contradição aparente que produz sentido: isso caracteriza o paradoxo.",
    "portugues-interpretacao",
    "A felicidade é tão oposta à vida, que estando nela, a gente esquece que vive.",
  ),
  q(
    4,
    P,
    "Formação vocabular",
    "Assinale a opção que relaciona de modo **incorreto** o adjetivo à locução adjetiva destacada.",
    [
      "Pessoas **que não se contentavam** com o que tinham - descontentes.",
      "Uma ferida **que não se apagava** - indelével.",
      "Havia algo em sua imagem **que não se podia distinguir** - indistinguível.",
      "Tinha a característica de alguém **que não se irrita com facilidade** – irascível.",
      "Água e álcool são elementos **que não se misturam** - imiscíveis.",
    ],
    3,
    "Irascível significa justamente o contrário: quem se irrita com facilidade. O “ir-” vem do radical latino irasci (irar-se), não é prefixo de negação.",
    "portugues-semantica",
  ),
  q(
    5,
    P,
    "Verbos de estado",
    "Assinale a opção em que o verbo destacado indica estado.",
    [
      "Ele virou-lhe as costas e **tornou** lentamente por onde viera.",
      "Piedade **ficou** à janela.",
      "Os curiosos **permaneciam** defronte de sua porta.",
      "Coitada! Devia **viver** bem aborrecida da sorte.",
      "Fazes mal em **andar** por aí com este sol.",
    ],
    3,
    "Em “viver aborrecida”, aborrecida é predicativo do sujeito e viver funciona como verbo de ligação, exprimindo estado. Em ficou à janela e permaneciam defronte da porta há circunstância de lugar (adjunto adverbial), não predicativo; tornou (= voltou) e andar indicam ação.",
    "portugues-semantica",
  ),
  q(
    6,
    P,
    "Pontuação",
    "Assinale a opção em que a vírgula se justifica pelo mesmo motivo do que em “se as duas tribos dividirem em paz as batatas do campo, não chegam a nutrir-se suficientemente e morrem de inanição”.",
    [
      "Acrescia que, em verdade, o doente parecia estar melhorando.",
      "Verdade é, disse ainda Rubião para defender o enfermo, verdade é que o cachorro merece a estima do dono.",
      "Quando este acudiu, já ele mudara outra vez de ideia.",
      "Espreitara uma deixa, e sai-lhe do testamento a massa toda dos bens.",
      "No dia seguinte, Maria Benedita declarou à prima que estava pronta a aprender piano e francês.",
    ],
    2,
    "No trecho de referência há uma oração subordinada adverbial condicional anteposta à principal. A mesma justificativa vale em “Quando este acudiu, …”, adverbial temporal anteposta. Em (A) e (B) há intercalação; em (D), coordenadas com sujeitos diferentes; em (E), adjunto adverbial deslocado — locução, não oração.",
    "portugues-pontuacao",
  ),
  q(
    7,
    P,
    "Variação linguística",
    "Nos versos de Luiz Gonzaga, o eu poético narra, em primeira pessoa, suas impressões sobre um determinado assunto.\nPara isso, ele utiliza construções linguísticas próprias, constatadas pelo uso",
    [
      "de uma norma linguística regional, a fim de caracterizar a cultura e o modo de vida do interior.",
      "do termo comparativo “qual”, que estabelece uma analogia entre terra e fogueira.",
      "de modalidade oral, que apresenta poucos recursos comunicativos, se comparada à modalidade escrita.",
      "do substantivo judiação, que reitera a tristeza do poeta nos trechos em destaque.",
      "de uma norma linguística desprestigiada, que serve para apontar a desigualdade social.",
    ],
    0,
    "Oiei, preguntei e uai marcam uma variedade regional, que caracteriza a cultura do interior. As alternativas que tratam a variedade como pobre ou desprestigiada contrariam o princípio de que nenhuma variedade é linguisticamente inferior.",
    "portugues-interpretacao",
    "Quando **oiei** a terra ardendo\nQual fogueira de São João\nEu **preguntei** a Deus do céu, **uai**\nPor que tamanha judiação?",
  ),
  q(
    8,
    P,
    "Interpretação literária",
    "Leia o fragmento de Fernando Pessoa reproduzido no texto de apoio.\nAssinale a opção correta sobre a interpretação dos versos em destaque.",
    [
      "Existe uma visão negativa do fazer poético, já que o poeta é descrito como “fingidor”.",
      "O jogo de palavras em fingidor - fingir dor - contribui para caracterizar o poeta como sujeito insubmisso ao sentimento.",
      "O fingimento é matéria de poesia, é a ferramenta da criação literária.",
      "O exercício de fazer poesia torna o poeta imune à dor.",
      "Há uma perspectiva irônica que se sustenta, sobretudo, em fingir a dor que, de fato, sente-se.",
    ],
    2,
    "Fingir, em Pessoa, não é mentir: é transfigurar a experiência em matéria estética. O poeta elabora a dor real até ela virar dor poética — o fingimento é a ferramenta da criação.",
    "portugues-interpretacao",
    "O poeta é um fingidor\nFinge tão completamente\nQue chega a fingir que é dor\nA dor que deveras sente.",
  ),
  q(
    9,
    P,
    "Orações reduzidas",
    "Sobre a estrutura sintática da frase em destaque, assinale a opção **incorreta**.",
    [
      "Existe uma oração subordinada que exerce função de sujeito em relação à oração principal.",
      "Nota-se uma oração subordinada substantiva, em que a segunda oração exerce função própria de um substantivo em relação à oração principal.",
      "Observa-se uma oração subordinada reduzida de infinitivo.",
      "Verifica-se a possibilidade de desenvolver a segunda oração em “que se esteja atento e forte”.",
      "Há uma oração subordinada que delimita a informação presente na oração principal.",
    ],
    4,
    "“Estar atento e forte” é oração subordinada substantiva subjetiva reduzida de infinitivo: ela é o sujeito de é preciso. Delimitar a informação da principal é próprio da oração adjetiva restritiva, que não ocorre aqui.",
    "portugues-sintaxe",
    "É preciso estar atento e forte.",
  ),
  q(
    10,
    P,
    "Funções sintáticas",
    "Assinale a opção em que o elemento destacado **não** funciona como adjunto adnominal.",
    [
      "Não admira que, fora de si, e andando rápido, desse um encontrão em certo homem **que ia devagar**.",
      "Catete adiante, lembrou-se que a casa **de Sofia** era na Praia do Flamengo.",
      "Após **alguns** instantes rápidos, abanou a cabeça voluntariamente.",
      "Este apertou-lhe a mão satisfeitíssimo; ia ver-se livre **de um sócio**.",
      "Mas diga-me uma coisa, essa proposta traz algum motivo **oculto**?",
    ],
    3,
    "Em “livre de um sócio”, a expressão completa o sentido do adjetivo livre: é complemento nominal. Adjetivo não recebe adjunto adnominal. Nas demais, os termos destacados restringem substantivos.",
    "portugues-sintaxe",
  ),
  q(
    11,
    P,
    "Discurso direto",
    "Sobre o uso do discurso direto, é **incorreto** afirmar que este procedimento",
    [
      "cria o efeito de realidade, já que a fala busca reproduzir o momento da enunciação.",
      "atribui o sentido de verdade, tendo em vista que prevalece o teor de preservação do discurso citado.",
      "delimita a fronteira entre o discurso do narrador e o discurso citado por meio de aspas, travessão e verbos de elocução.",
      "demarca a soberania do narrador, pois ele interpreta a fala citada, absorvida no fio de seu discurso.",
      "precisa transpor as palavras do discurso citado, tal qual foram enunciadas originalmente.",
    ],
    3,
    "A fala absorvida e interpretada no fio do discurso do narrador caracteriza o discurso indireto. No direto, a voz do outro entra preservada e separada por marcas gráficas.",
    "portugues-interpretacao",
    "O uso excessivo de telas faz mal à saúde da mente e do corpo e os efeitos podem ser ainda mais danosos nas duas primeiras décadas de vida:\n\n- Como tudo, o problema está no excesso e na falta de controle adequado, afirma o psicólogo Thiago Viola, do Instituto do Cérebro do Rio Grande do Sul.\n\nbbc.com (adaptado)",
  ),
  q(
    12,
    P,
    "Regência verbal",
    "Assinale a opção que apresenta corretamente a regência dos verbos.",
    [
      "Não faz sentido obedecer a leis absurdas.",
      "Admito que me simpatizei muito com a nova professora de Literatura.",
      "Nossos vizinhos se mudaram e residem agora à rua das Laranjeiras.",
      "Possuía uma dívida com o açougueiro, paguei-o assim que pude.",
      "Vovó sempre lembra do aniversário de todos os seus netos.",
    ],
    0,
    "Obedecer é transitivo indireto e rege a preposição a. Nas demais: simpatizar não é pronominal (simpatizei com); residir pede em (na rua); pagar pessoa pede objeto indireto (paguei-lhe, pois o pronome retoma o açougueiro); e lembrar só é indireto quando pronominal (lembra-se do aniversário).",
    "portugues-normativa",
  ),
  q(
    13,
    I,
    "Reading comprehension",
    "Consider the following affirmatives:\n1. The TEXT can just be found online.\n2. The tips on this text are only for fresh graduates.\n3. It is a printed book.\n4. Professors, last-year students and consultants who are skilled at guiding business recommend the book.\n\nAccording to the TEXT,",
    [
      "only 2 and 4 are false.",
      "only 1 and 4 are true.",
      "only 1, 3 and 4 are true.",
      "only 1, 2 and 4 are false.",
      "only 3 and 4 are true.",
    ],
    1,
    "Item 1 é verdadeiro (“eBook Kindle only”) e o item 4 também (“Recommended by university professors, last-year students, as well as seasoned consultants”). O item 2 é falso, pois o texto atende também quem tem 20 anos de experiência, e o 3 é falso, já que não é livro impresso.",
    "ingles-compreensao",
    TXT_CONSULTING,
  ),
  q(
    14,
    I,
    "Pronouns",
    "In the excerpt in TEXT “Recommended by university professors, last-year students, as well as seasoned consultants. Even my mom says you have to read this book, or you have to answer to **her**!”\nThe pronoun her refers to",
    ["consultants.", "book.", "students.", "professors.", "mom."],
    4,
    "Her é singular, feminino e [+humano]. Consultants, students e professors são plurais; book é [−humano]. O antecedente é mom.",
    "ingles-referencia",
    TXT_CONSULTING,
  ),
  q(
    15,
    I,
    "Reading comprehension",
    "What information is in TEXT?",
    [
      "Tips on an in-person appraisal to be a successful IT consultant.",
      "A review on a guide to foster the possibility of being successful in finding your Dream Job in IT Consulting, despite your experience.",
      "Challenge only beginners to read a guide well written and recommended by professors in the IT scenario.",
      "The reasons one should buy the guide to be a successful IT consultant abroad.",
      "It is a well explained guide to enhance people’s desire to find a dream internship despite their social status.",
    ],
    1,
    "O texto divulga um guia de carreira útil a leitores de qualquer nível de experiência — daí “despite your experience”. As demais restringem indevidamente: só iniciantes, só no exterior, ou estágio em vez de emprego.",
    "ingles-compreensao",
    TXT_CONSULTING,
  ),
  q(
    16,
    I,
    "Connectives",
    "“With this book, you can find out why your current job is not satisfying your career aspirations **and** turn your career around for the better!”\nThe discourse marker and used in TEXT is similar in meaning to",
    ["hence.", "whereas.", "unless.", "moreover.", "meanwhile."],
    3,
    "And soma um segundo benefício: valor aditivo, equivalente a moreover. Hence é consequência, whereas é contraste, unless é condição e meanwhile é tempo.",
    "ingles-referencia",
    TXT_CONSULTING,
  ),
  q(
    17,
    I,
    "Reading comprehension",
    "By the end of TEXT six people assessed the guide. One of them said that he should have had the opportunity to study on the guide on the brick of graduating.\nChoose the person who said that.",
    [
      "Saku Sikiö",
      "Petteri Laamanen",
      "Samuli Pekkola",
      "Janita Kingelin",
      "Teijo Kelander",
    ],
    4,
    "A pergunta parafraseia “This is the book I would have needed on the verge of graduation!”, depoimento assinado por Teijo Kelander.",
    "ingles-compreensao",
    TXT_CONSULTING,
  ),
  q(
    18,
    I,
    "Connectives",
    "In the sentence taken from TEXT “The book gives a strong and realistic description of IT consultancy. **Thus**, every IT student should read the book before they graduate as it will increase their probability of landing a dream job.”\nThe underlined linker introduces",
    [
      "a condition.",
      "an example.",
      "an effect.",
      "an order.",
      "a reason.",
    ],
    2,
    "Thus equivale a therefore: introduz consequência, efeito do que foi dito antes.",
    "ingles-referencia",
    TXT_CONSULTING,
  ),
  q(
    19,
    I,
    "Academic reading",
    "According to TEXT it can be said that",
    [
      "This essay is concerned not only about apps but also about successful web developers.",
      "The Text is an academic piece of writing.",
      "Artificial Intelligence has created app store.",
      "App developers are addicted to AppEco.",
      "AppEco is a website known around the world by foreigners.",
    ],
    1,
    "Título, autores, seção Abstract, descrição de método e DOI identificam um artigo acadêmico. As demais afirmam o que o texto não diz: ele trata de apps, não de web developers, e AppEco é um modelo de simulação, não um site.",
    "ingles-compreensao",
    TXT_APPECO,
  ),
  q(
    20,
    I,
    "Word classes",
    "In the excerpt “In this work we use AppEco to simulate Apple's iOS app ecosystem and investigate common developer strategies, evaluating them in terms of downloads received, app diversity, and adoption **rate**.\nChoose the correct option according to TEXT.",
    [
      "The word rate means a measure and it’s a discourse marker.",
      "The word rate means to quantify and it’s an adjective.",
      "The word rate means to quantify and it’s a subject.",
      "The word rate means to charge and it’s a verb.",
      "The word rate means a measure and it’s a noun.",
    ],
    4,
    "Rate vem precedido do substantivo adoption, que o modifica: é o núcleo do sintagma, portanto substantivo, com o sentido de medida/taxa de adoção.",
    "ingles-vocabulario",
    TXT_APPECO,
  ),
  q(
    21,
    I,
    "Modal verbs",
    "In the sentences, “With hundreds of thousands of apps in these online stores, what strategy **should** a developer use to be successful? **Should** they innovate, make many similar apps, optimize their own apps or just copy the apps of others?”.\nThe modal “should”, used in TEXT, expresses the idea of:",
    [
      "Absence of obligation",
      "Suggestion",
      "Offer",
      "Possibility",
      "Obligation",
    ],
    1,
    "O autor levanta hipóteses de conduta recomendável, não impõe nem oferece nada: should tem aqui valor de conselho/sugestão. Ausência de obrigação seria don't have to; obrigação forte, must.",
    "ingles-modais",
    TXT_APPECO,
  ),
  q(
    22,
    I,
    "Vocabulary",
    "The word “browse” in “user agents **browse** the store and download the apps.”, taken from TEXT, is a verb.\nThe same word can also be used as a noun in sentence:",
    [
      "I stopped in several bookstores to ___.",
      "I usually ___ the internet for a couple of hours each evening.",
      "The brochure is well worth a ___.",
      "There are plenty of biographies for him to ___ over.",
      "I always ___ in an up-market antique shop.",
    ],
    2,
    "Em “worth a ___”, a lacuna vem depois do artigo a, posição de substantivo. Nas demais, a lacuna segue to ou um sujeito, posições de verbo.",
    "ingles-vocabulario",
    TXT_APPECO,
  ),
  q(
    23,
    I,
    "Pronouns",
    "The pronoun “it” in “**It** can print up to 20 pages per minute from any PC, Pocket PC, or Windows Mobile handheld”, taken from TEXT, refers to",
    [
      "Computer.",
      "Pocket PC.",
      "Window Mobile handheld.",
      "MPrint MW-260.",
      "Bluetooth.",
    ],
    3,
    "It retoma o sujeito recém-apresentado, a impressora MPrint MW-260. PC, Pocket PC e handheld aparecem como complementos de “from any”, não como sujeito.",
    "ingles-referencia",
    TXT_PRINTER,
  ),
  q(
    24,
    I,
    "Vocabulary",
    "In the sentence “No word on pricing or availability, but this is **a 1-pound printer** we wouldn't mind adding to our travel bag”.\nThe expression “... a 1-pound printer” taken from TEXT is referring to",
    [
      "The weight of the printer.",
      "The price of the printer.",
      "The printer serial number.",
      "The printer stock availability.",
      "The printer sale.",
    ],
    0,
    "Pound é unidade de peso (≈ 453 g), e o contexto confirma: falar em levar na travel bag remete ao peso. Além disso, o texto diz explicitamente “No word on pricing”, o que elimina a alternativa do preço.",
    "ingles-vocabulario",
    TXT_PRINTER,
  ),
  q(
    25,
    R,
    "Equivalência lógica",
    "A proposição logicamente equivalente à proposição “Se Cesar é fã de futebol então ele assiste a muitos jogos” é",
    [
      "Cesar é fã de futebol e assiste a muitos jogos.",
      "Cesar gosta de futebol porque assiste a muitos jogos.",
      "Cesar gosta de assistir jogos por ser fã de futebol.",
      "Se Cesar não assiste a muitos jogos então ele não é fã de futebol.",
      "Se Cesar não é fã de futebol então ele não assiste a muitos jogos.",
    ],
    3,
    "A equivalente de P → Q é a contrapositiva ~Q → ~P. A alternativa (E) é a inversa (~P → ~Q), que não equivale à condicional.",
    "rlm-logica",
  ),
  q(
    26,
    R,
    "Equações",
    "Dois sistemas monitoram a variação de temperatura dos servidores em um data center. Um sistema registra variações positivas (aquecimento) e o outro registra variações negativas (resfriamento). Certo dia, a soma dessas variações foi de 1 grau Celsius, indicando que o ambiente se manteve praticamente estável. No entanto, a soma dos quadrados dessas variações foi de 313, o que revela uma diferença significativa entre o maior valor positivo e o menor valor negativo registrados.\nA diferença entre esses valores é",
    ["20.", "25.", "30.", "35.", "40."],
    1,
    "De (x−y)² = (x+y)² − 4xy e xy = [(x+y)² − (x²+y²)]/2 = (1 − 313)/2 = −156, vem (x−y)² = 1 + 624 = 625, logo x − y = 25. As raízes são 13 e −12.",
    "rlm-algebra",
  ),
  q(
    27,
    R,
    "Média ponderada",
    "Uma determinada escola adota o sistema de pesos por bimestre para o cálculo da média anual. O primeiro bimestre tem peso 1, o segundo, 2, o terceiro, 3, e o quarto, 4. Assim, para calcular a média anual, um estudante deve efetuar a soma de cada uma de suas notas bimestrais multiplicadas pelos seus respectivos pesos e dividir por 10. Para ser aprovado, um aluno precisa ter média anual, no mínimo, igual a 7,0.\nArnaldo tirou notas 4,0; 6,0; 8,0; 8,0 nos 4 bimestres, não necessariamente nessa ordem. Para que Arnaldo seja aprovado, a sua menor nota deve ter sido tirada no",
    [
      "1º bimestre, necessariamente.",
      "1º ou 2º bimestres, necessariamente.",
      "2º bimestre, necessariamente.",
      "3º bimestre, necessariamente.",
      "3º ou 4º bimestre, necessariamente.",
    ],
    1,
    "É preciso soma ponderada ≥ 70. Com a nota 4 no peso 1: 4+12+24+32 = 72 ✔. No peso 2: 8+6+24+32 = 70 ✔. No peso 3: 66 ✗. No peso 4: 62 ✗. Logo, 1º ou 2º bimestre.",
    "rlm-proporcoes",
  ),
  q(
    28,
    R,
    "Porcentagem",
    "O preço de venda de certo item de consumo sofreu dois aumentos mensais consecutivos, sendo o primeiro de 30% e o segundo de 10%.\nSobre a taxa média de aumento mensal nesse período, é correto afirmar que",
    [
      "é maior que 19% e menor que 20%.",
      "é igual a 20%.",
      "é maior que 20% e menor que 21%.",
      "é igual a 21,5%.",
      "é igual a 43%.",
    ],
    0,
    "O fator acumulado é 1,30 × 1,10 = 1,43. A taxa média é a média geométrica: √1,43 − 1 ≈ 19,58%. A alternativa dos 20% é a armadilha de quem calcula a média aritmética.",
    "rlm-proporcoes",
  ),
  q(
    29,
    R,
    "Razão e proporção",
    "Arnaldo e Bernaldo associaram-se em um determinado negócio. Arnaldo entrou com R$ 12.000,00 e Bernaldo com R$ 13.000,00.\nSe perderem R$ 50.000,00, caberá a Arnaldo o prejuízo de",
    [
      "R$ 18.000,00",
      "R$ 20.000,00",
      "R$ 24.000,00",
      "R$ 26.000,00",
      "R$ 28.000,00",
    ],
    2,
    "O prejuízo se reparte na razão do capital: 12.000/25.000 = 0,48; 0,48 × 50.000 = R$ 24.000. Confere: 24.000 + 26.000 = 50.000.",
    "rlm-proporcoes",
  ),
  q(
    30,
    R,
    "Combinatória",
    "Numa certa região há alguns vilarejos de maneira que cada dupla de vilarejos possui uma única estrada que os conecta. Observe o exemplo para cinco vilarejos em que cada casinha representa um vilarejo e cada segmento de reta representa uma estrada.\nConsidere que nessa região há inicialmente x vilarejos e que 2 novos vilarejos estejam se desenvolvendo. Por essa razão, 17 novas estradas estão sendo construídas.\nNessas condições, o número x vale",
    ["6.", "7.", "8.", "9.", "10."],
    2,
    "O total de estradas é C(n,2) = n(n−1)/2. Passando de x para x+2 vilarejos, as novas estradas são C(x+2,2) − C(x,2) = 2x + 1. De 2x + 1 = 17 vem x = 8.",
    "rlm-algebra",
    "[Figura do caderno] Cinco casinhas dispostas em pentágono, ligadas duas a duas por segmentos de reta — 10 estradas ao todo, que é C(5,2).",
  ),
  q(
    31,
    A,
    "Tecnologia e meio ambiente",
    "Sobre os aspectos apresentados no texto, julgue os itens a seguir:\n( ) As tecnologias digitais não são apenas fonte de soluções para problemas ligados ao meio ambiente, mas também consistem em fontes de impactos negativos.\n( ) O texto defende que todos os avanços tecnológicos representam invariavelmente benefícios para o meio ambiente.\n( ) Os data centers representam cerca de metade do consumo de energia dos ecossistemas digitais, termo cunhado para definir a relação entre infraestrutura digital, ferramentas e seres humanos.\n\nAs afirmativas são, respectivamente,",
    ["V – F – V.", "F – V – V.", "V – V – F.", "F – F – V.", "V – V – V."],
    0,
    "O texto mostra as duas faces da tecnologia (I verdadeiro) e, ao expor o consumo dos data centers, contraria a ideia de benefício invariável (II falso). III é verdadeiro: os 2% citados referem-se à eletricidade de todo o planeta, não ao consumo do ecossistema digital, dentro do qual os data centers respondem por cerca de metade.",
    "atualidades-ambiente",
    "A adoção de tecnologias digitais muitas vezes é vista como resposta para dilemas ambientais. O avanço da internet, por exemplo, permitiu a diminuição do uso de papel, que foi substituído por bytes. Entretanto, os data centers ao redor do mundo consomem aproximadamente 2% de toda eletricidade do planeta, emitindo por exemplo, quantidades similares de carbono, comparadas as da indústria aérea.",
  ),
  q(
    32,
    A,
    "G20",
    "Sobre o Grupo apresentado no texto, julgue as afirmativas:\nI. Consiste num dos maiores blocos econômicos do planeta, sendo seu principal objetivo o livre comércio, sendo superado apenas pela União Europeia.\nII. Representa um fórum internacional de cooperação econômica, que possibilita entre outras coisas, debates sobre temas financeiros, fome, meio ambiente e desigualdades.\nIII. Congrega um bloco supranacional com objetivo de alinhar políticas macroeconômicas, éticas e militares, perante a comunidade internacional.\n\nEstá correto o que se afirma em",
    [
      "I, apenas.",
      "II, apenas.",
      "I e II, apenas.",
      "I e III, apenas.",
      "I, II e III.",
    ],
    1,
    "Só II está correta. O G20 é fórum de cooperação econômica, não bloco econômico de livre comércio (I) nem bloco supranacional com alinhamento militar (III) — supranacionalidade implicaria cessão de soberania, o que não ocorre.",
    "atualidades-geopolitica",
    "Na reunião de cúpula do G2 que ocorre no Brasil, país que exerce a presidência rotativa até o fim de novembro, o tema principal dos debates é a construção de um Mundo Justo e um Planeta Sustentável. O governo brasileiro deseja colocar o combate às desigualdades no centro das discussões entre os países membros.\n\n[Nota: o caderno oficial traz “G2”; trata-se de erro de digitação da banca para G20.]",
  ),
  q(
    33,
    A,
    "Proteção de dados",
    "Sobre a denúncia, os dados podem ter o seguinte destino:\nI. Realização de publicidade direcionada a determinados perfis de consumidores, considerando a faixa etária, o sexo e perfis de saúde.\nII. Execução de publicidade para empresas do grupo econômico e para terceiros, gerando lucro indevido sem autorização ou conhecimento dos clientes.\nIII. Pesquisas da indústria farmacêutica para produção de remédios mais baratos, democratizando o acesso a tratamentos de saúde através do programa Farmácia Popular.\n\nEstá correto o que se afirma em",
    [
      "I, apenas.",
      "III, apenas.",
      "I e II, apenas.",
      "I e III, apenas.",
      "I, II e III.",
    ],
    2,
    "A denúncia trata de coleta indevida e comercialização de dados, o que sustenta I e II. III descreve finalidade legítima e de interesse público, estranha ao caso relatado.",
    "atualidades-consumo-dados",
    "A Secretaria Nacional do Consumidor notificou uma grande rede de Farmácias para prestar esclarecimentos a respeito de práticas de tratamento indevido de dados pessoais de seus consumidores. O fato ocorreu por denúncia publicada em um grande portal de comunicação, que expôs a coleta inadequada de informações e sua comercialização.",
  ),
  q(
    34,
    A,
    "Cidades-esponja",
    "A nova legislação adotará mecanismos sustentáveis com intuito de:\n( ) Reduzir a sobrecarga dos sistemas tradicionais de drenagem possibilitando a aproximação de autossuficiência hídrica.\n( ) Direcionar as águas pluviais que causam transtornos, para o reabastecimento de redes subterrâneas.\n( ) Diminuir a presença da infraestrutura cinza na canalização de rios, com a construção de jardins de chuva, melhorando a impermeabilização de grandes áreas.\n\nAs afirmativas são, respectivamente,",
    ["V – F – V.", "F – V – V.", "V – V – V.", "F – F – V.", "V – V – F."],
    4,
    "As duas primeiras descrevem corretamente a cidade-esponja. A terceira é falsa: jardins de chuva aumentam a permeabilidade do solo — impermeabilizar é justamente o problema que o modelo combate.",
    "atualidades-ambiente",
    "O município do Rio de Janeiro vai aplicar o conceito de cidade-esponja para diminuir os efeitos das enchentes. Esse modelo é usado em várias cidades do mundo para evitar tragédias ambientais, constituindo o ponto central de uma lei municipal, sancionada parcialmente em julho de 2024.",
  ),
  q(
    35,
    A,
    "Racismo ambiental",
    "Sobre o tema abordado no texto, julgue os itens a seguir:\nI. É flagrante violação da Constituição, com a distribuição injusta da poluição, submetendo de forma desigual, em razão da raça, determinadas populações a precárias condições de vida.\nII. Um projeto de desenvolvimento sustentável deve ser baseado em inovações tecnológicas, mantendo a lógica de consumo do atual modelo econômico, proporcionando justiça social para todos.\nIII. O conceito de racismo ambiental está ligado aos danos ambientais e sua imposição recorrente em comunidades habitadas principalmente por populações negras e pobres.\n\nEstá correto o que se afirma em",
    [
      "I, apenas.",
      "III, apenas.",
      "II e III, apenas.",
      "I e III, apenas.",
      "I, II e III.",
    ],
    3,
    "I e III estão corretas. II é falsa: manter a lógica de consumo do modelo econômico atual contraria a própria noção de desenvolvimento sustentável — é o chamado solucionismo tecnológico.",
    "atualidades-ambiente",
    "A Constituição Federal é o documento jurídico-político que limita o poder estatal e o regulamenta. O art. 225 da Carta Magna confere a todos o direito ao meio ambiente equilibrado, impondo ao Poder Público e à coletividade preservá-lo, estabelecendo uma série de diretrizes aptas a assegurar a disposição.",
  ),
  q(
    36,
    L,
    "Marco Civil",
    "A Lei nº 12.965, de 23 de abril de 2014, estabelece princípios, garantias, direitos e deveres para o uso da Internet no Brasil. Ao tratar da proteção aos registros, aos dados pessoais e às comunicações privadas, tal diploma legal positiva sanções específicas para o descumprimento do que prescreve.\nA respeito disso, é correto afirmar que",
    [
      "as sanções só podem ser aplicadas isoladamente, exceto quando o caso reclamar a mais grave que, então, poderá ser cumulada com outras.",
      "a previsão de advertência contempla duas faces: uma repressiva e outra corretiva, na medida em que se indica prazo para adoção de medidas de regularização.",
      "a censura deve ser imposta à pessoa natural, proprietária do provedor, quando este burlar a proibição de coleta de dados pessoais anteriormente aplicada.",
      "na previsão de multa, o quanto é fixado em 10% (dez por cento) do faturamento do grupo econômico no Brasil, extraído da média dos últimos três exercícios, excluídos os tributos.",
      "a Lei nº 12.965, de 23 de abril de 2014, possui um vácuo legislativo com relação a empresas estrangeiras, porque não traz regramento sancionatório para suas condutas infringentes.",
    ],
    1,
    "Art. 12, I: a advertência indica prazo para medidas corretivas — é sancionatória e corretiva ao mesmo tempo. As sanções podem ser aplicadas isolada ou cumulativamente; a multa é de ATÉ 10% sobre o ÚLTIMO exercício; a lei não prevê censura; e o parágrafo único do art. 12 responsabiliza solidariamente filial ou estabelecimento de empresa estrangeira no País.",
    "leg-marco-civil",
  ),
  q(
    37,
    L,
    "LGPD - sanções",
    "As sanções administrativas estão positivadas na Lei nº 13.709, de 14 de agosto de 2018 (Lei Geral de Proteção de Dados Pessoais - LGPD), em capítulo intitulado de fiscalização.\nCom relação ao quadro legal sancionatório mencionado, é correto afirmar que",
    [
      "é possível a aplicação de sanções sem a formalização de processo administrativo correspondente, em caso no qual se constate que o agente de tratamento de dados é violador contumaz da citada lei.",
      "a lei contempla expressamente diversos parâmetros e critérios a serem considerados na aplicação da sanção, como, por exemplo, a gravidade da infração, a boa fé e o fato de o infrator ter nacionalidade estrangeira.",
      "eventual aplicação da sanção de multa simples a órgão público deverá considerar a arrecadação tributária do ente federativo a que pertença e o orçamento afetado para o desenvolvimento de suas atividades.",
      "o produto da arrecadação das multas aplicadas pela Autoridade Nacional de Proteção de Dados, inscritas ou não em dívida ativa, será destinado diretamente às pessoas naturais cujo direito à proteção de dados foi violado.",
      "em caso de vazamento individual, a lei contempla a possibilidade de conciliação direta entre controlador e titular, estando aquele, na hipótese de inexistência de acordo, sujeito à aplicação das penalidades previstas no capítulo mencionado.",
    ],
    4,
    "Art. 52, §7º: vazamentos individuais podem ser objeto de conciliação direta entre controlador e titular e, não havendo acordo, aplicam-se as penalidades do artigo. Não há sanção sem processo administrativo; nacionalidade estrangeira não é parâmetro do §1º; e o produto das multas vai ao Fundo de Direitos Difusos, não diretamente aos titulares.",
    "leg-lgpd",
  ),
  q(
    38,
    L,
    "ANPD e CNPD",
    "A Lei nº 13.709, de 14 de agosto de 2018, trouxe ao ordenamento jurídico duas figuras jurídicas importantes no sistema de proteção de dados pessoais.\nSobre o desenho legal da Autoridade Nacional de Proteção de Dados e o Conselho Nacional de Proteção de Dados Pessoais e da Privacidade, é correto afirmar que",
    [
      "atualmente, Conselho Nacional de Proteção de Dados Pessoais e da Privacidade possui natureza de empresa pública federal e a Autoridade Nacional de Proteção de Dados é órgão da administração pública federal.",
      "o Conselho Diretor é composto de representantes, titulares e suplentes, da Câmara dos Deputados, do Comitê Gestor da Internet do Brasil, do Senado Federal, do Conselho Nacional de Justiça e do Conselho Nacional do Ministério Público.",
      "o Conselho Nacional de Proteção de Dados Pessoais e da Privacidade possui atribuição de sugerir ações a serem realizadas pela Autoridade Nacional de Proteção de Dados e disseminar o conhecimento sobre a proteção de dados pessoais e da privacidade à população.",
      "os membros do Conselho Nacional de Proteção de Dados Pessoais e da Privacidade somente perderão seus cargos em virtude de renúncia, condenação judicial transitada em julgado ou pena de demissão decorrente de processo administrativo disciplinar.",
      "a Autoridade Nacional de Proteção de Dados é uma das integrantes do Conselho Nacional de Proteção de Dados Pessoais e da Privacidade, figurando como conselheira presidente, na hipótese de nomeação pelo Presidente da República.",
    ],
    2,
    "São atribuições expressas do CNPD (art. 58-B, III e V). O Conselho Diretor é órgão DA ANPD, formado por diretores nomeados pelo Presidente da República após aprovação do Senado — os representantes da Câmara, do CNJ e do CNMP integram o CNPD, que é outra figura.",
    "leg-lgpd",
  ),
  q(
    39,
    L,
    "LAI",
    "A Lei nº 12.527, de 18 de novembro de 2011, dispõe sobre as restrições de acesso à informação. Nesses termos, a lei traz diversos temas que permeiam a classificação da informação.\nSobre esse assunto, é correto afirmar que",
    [
      "as informações podem ser classificadas como ultrassigilosas, sigilosas ou reservadas, sendo certo que a decisão respectiva é discricionária, porquanto a lei não prevê balizas.",
      "a decisão de classificação de uma informação é pública e de acesso a qualquer interessado, independentemente de demonstração de interesse, embora classificada a informação.",
      "findo o prazo de classificação ou ocorrido o evento constituidor do termo final, para que o acesso se torne público são necessários procedimento próprio e decisão específica.",
      "a informação que verse sobre conduta que implique violação dos direitos humanos praticada por agentes públicos ou a mando de autoridades públicas não pode ser objeto de restrição de acesso.",
      "a lei permite a desclassificação, mas não a redução de prazo de informação classificada, devendo a reavaliação ser feita pela autoridade classificadora ou outra superior, mediante provocação ou de ofício.",
    ],
    3,
    "É o art. 21, parágrafo único, da LAI. As demais: os graus são ultrassecreta, secreta e reservada, com hipóteses taxativas no art. 23; a decisão de classificar segue o sigilo do que classifica (art. 28, parágrafo único); findo o prazo o acesso é automático (art. 24, §4º); e a reavaliação pode desclassificar OU reduzir o prazo (art. 29, §2º).",
    "leg-lai",
  ),
  q(
    40,
    L,
    "Crime informático",
    "Um hacker, por ter conseguido subtrair previamente a senha de acesso, invadiu o tablet do vice-Presidente da Câmara dos Deputados e, sem este saber, adulterou informações importantes relativas ao funcionamento da Casa Parlamentar, trazendo grande prejuízo político. Identificada a pessoa, o aludido congressista ajuizou queixa-crime. Ao final do processo penal, o hacker foi condenado com aumento de pena de um terço, por conta do sujeito passivo do delito.\nQuanto à situação descrita, é correto afirmar que",
    [
      "a deflagração da ação penal está incorreta, porquanto deveria ter sido iniciada pelo Ministério Público.",
      "na fixação da pena, deveria ter havido um aumento de metade da pena, já que da invasão resultou prejuízo político.",
      "o crime de invasão de dispositivo informático possui como elementar a exigência de o tablet estar conectado à rede de computadores.",
      "o aumento da pena deveria ter sido de dois terços da pena, por conta do ilícito penal ter sido praticado contra o vice-Presidente da Câmara dos Deputados.",
      "para configuração do delito trazido pelo art. 2º, da Lei nº 12.737, de 30 de novembro de 2012 (art. 154-A, do Código Penal), é preciso a efetiva adulteração das informações.",
    ],
    0,
    "Art. 154-B do CP: procede-se mediante representação, salvo se o crime é cometido contra a administração pública — caso dos autos, pois atingiu o funcionamento da Casa Parlamentar. A ação é pública incondicionada e caberia ao Ministério Público, por denúncia, e não queixa-crime. O crime é formal: não exige conexão à rede nem adulteração efetiva.",
    "leg-marco-civil",
  ),
  q(
    41,
    T,
    "Design e arquitetura",
    "Em relação ao Design e arquitetura de Software, assinale a opção correta.",
    [
      "O Design de Software é o processo de codificação de funcionalidades seguindo diretamente os requisitos do usuário, sem envolver abstrações ou estruturas maiores.",
      "No Design de Software de baixo nível, o foco está na criação da estrutura geral do sistema, incluindo a definição de módulos e sua interação.",
      "O Design de Software de alto nível trata de decisões relacionadas à implementação de funções e métodos específicos dentro dos componentes de um sistema.",
      "A principal diferença entre Design e Arquitetura de Software é que a Arquitetura foca em decisões amplas e estruturais, enquanto o Design foca em decisões detalhadas e específicas.",
      "A Arquitetura de Software é um conceito aplicado apenas em projetos de grande escala, sendo irrelevante para sistemas menores e simples.",
    ],
    3,
    "Arquitetura trata da estrutura e das decisões de maior custo de mudança; Design detalha componentes e implementação. As alternativas (B) e (C) invertem alto e baixo nível, e (E) erra ao supor que sistema pequeno não tem arquitetura.",
    "esp-arquitetura",
  ),
  q(
    42,
    T,
    "Blockchain",
    "Em um sistema de blockchain tradicional, cada bloco armazena informações importantes para garantir a integridade e a validação das transações.\nConsiderando a estrutura de blockchains públicas como Bitcoin e Ethereum, o elemento que **não** é armazenado diretamente em um bloco",
    [
      "é o Hash do bloco anterior.",
      "são as Assinaturas digitais das transações.",
      "é o Registro de saldo das carteiras participantes.",
      "é o Timestamp (carimbo de tempo).",
      "são os Dados das transações.",
    ],
    2,
    "A cadeia registra transações, não extratos. No Bitcoin o saldo é derivado das UTXOs não gastas; no Ethereum vive no estado global mantido pelos nós, fora do corpo do bloco. Hash anterior, timestamp, dados e assinaturas ficam no bloco.",
    "esp-plataformas",
  ),
  q(
    43,
    T,
    "Engenharia de requisitos",
    "Durante o processo de engenharia de requisitos em um projeto de desenvolvimento de software para um sistema bancário, o analista de requisitos identificou que era necessário que a função de saldo de conta passasse a ser realizada em tempo real. Para isso, ele utilizou uma entrevista com o gerente do projeto e uma sessão de brainstorming com a equipe de desenvolvimento.\nNesse contexto, é correto afirmar que",
    [
      "o requisito identificado é funcional, pois descreve uma funcionalidade específica do sistema que o usuário deve ser capaz de executar.",
      "o requisito identificado é não funcional, pois está relacionado ao desempenho do sistema ao apresentar informações em tempo real.",
      "a entrevista com o gerente do projeto é um exemplo de técnica de prototipação, uma vez que visa a construção de um modelo para validar os requisitos.",
      "a sessão de brainstorming com a equipe de desenvolvimento é uma técnica inadequada para elicitação de requisitos, pois deve-se usar apenas entrevistas formais com os usuários finais.",
      "o processo de engenharia de requisitos geralmente ocorre após a fase de implementação do software, pois é necessário ter o software em funcionamento para capturar as necessidades dos usuários.",
    ],
    1,
    "Consultar saldo é funcional, mas “em tempo real” é restrição de desempenho — atributo de qualidade, portanto requisito não funcional. Brainstorming é técnica válida de elicitação, entrevista não é prototipação, e a engenharia de requisitos precede a implementação.",
    "esp-engenharia",
  ),
  q(
    44,
    T,
    "Web services",
    "Uma empresa de comércio eletrônico decidiu integrar seus sistemas de pagamento usando uma arquitetura orientada a serviços e web services como a tecnologia de integração. A ação correta na implementação dessa solução para garantir baixo acoplamento e alta interoperabilidade entre os sistemas seria",
    [
      "usar RESTful Web Services, que permitem a comunicação entre os sistemas de forma leve e independente de plataforma, promovendo maior flexibilidade e baixo acoplamento entre os serviços.",
      "implementar serviços SOAP sem definição de contratos formais para aumentar a flexibilidade da comunicação entre o sistema de pagamento e os provedores.",
      "utilizar interoperabilidade de rede entre os serviços de pagamento e os provedores, pois isso assegura baixo acoplamento e que as mudanças em um dos serviços se reflitam diretamente no outro, evitando inconsistências.",
      "definir um modelo de arquitetura monolítica com todos os provedores de pagamento integrados diretamente ao sistema, eliminando a necessidade de comunicação via Web Services e, assim, melhorando o desempenho.",
      "empregar Web Services com RPC (Remote Procedure Call) e WDSL para garantir que a chamada dos métodos seja feita diretamente entre o sistema de pagamento e os provedores, simplificando a integração.",
    ],
    0,
    "REST é leve, independente de plataforma e favorece baixo acoplamento. SOAP sem contrato formal quebra a interoperabilidade, que depende do WSDL; e “mudanças em um serviço se refletirem diretamente no outro” é a definição de alto acoplamento, exatamente o que se quer evitar.",
    "esp-arquitetura",
  ),
  q(
    45,
    T,
    "Servidores web",
    "No contexto da arquitetura de aplicações para ambientes web, é fundamental compreender a função e a distinção entre os diversos tipos de servidores utilizados, como o servidor de aplicações e o servidor web.\nAssinale a opção que apresenta corretamente as características dos servidores na arquitetura web.",
    [
      "O servidor de aplicações é responsável exclusivamente pelo envio de páginas estáticas (HTML, CSS, JavaScript), enquanto o servidor web processa lógica de negócios e acessa bancos de dados.",
      "O servidor web tem como principal função processar requisições HTTP e enviar páginas estáticas ou dinâmicas ao cliente, enquanto o servidor de aplicações fornece uma camada intermediária para execução de lógica de negócios e integração com bancos de dados.",
      "O servidor de aplicações é responsável por gerenciar o tráfego HTTP, enquanto o servidor web faz o papel de intermediar requisições a sistemas legados e bancos de dados.",
      "O servidor web e o servidor de aplicações são essencialmente o mesmo, pois ambos servem conteúdos dinâmicos e processam a lógica de negócios da aplicação.",
      "O servidor de aplicações apenas faz o balanceamento de carga entre diferentes servidores web, sem processar requisições de lógica de negócios ou conectar-se a bancos de dados.",
    ],
    1,
    "É a separação usual: o servidor web (Apache, Nginx) atende HTTP e serve conteúdo; o servidor de aplicações (Tomcat, WildFly) executa a lógica de negócio e integra bancos. As demais invertem os papéis ou os confundem.",
    "esp-arquitetura",
  ),
  q(
    46,
    T,
    "Métricas de software",
    "Em projetos de desenvolvimento de software, a escolha da técnica de mensuração de tamanho e esforço é essencial para a gestão eficiente e o planejamento adequado das atividades.\nNesse contexto, é correto afirmar que",
    [
      "o Ponto de Função oferece uma mensuração objetiva e independente do time de desenvolvimento.",
      "os Story Points permitem uma melhor padronização de estimativas entre diferentes projetos e times.",
      "o Ponto de Função é mais flexível, já que leva em conta o contexto subjetivo do time ao estimar o esforço.",
      "os Story Points são mais adequados para contratos formais de desenvolvimento, como projetos com escopo fechado e orçamentos rígidos.",
      "o Ponto de Função permite uma mensuração rápida, já que a estimativa é feita com base no esforço percebido pelo time.",
    ],
    0,
    "Ponto de Função mede tamanho funcional por norma (ISO/IEC 20926), de forma objetiva e independente da equipe. Story Points são relativos ao time, não se comparam entre times e não servem bem a contrato de escopo fechado.",
    "esp-agil",
  ),
  q(
    47,
    T,
    "Métodos ágeis",
    "Em um projeto de alta complexidade, sujeito a mudanças frequentes nos requisitos e com a necessidade de entregas rápidas em ciclos incrementais, a metodologia ágil mais adequada para priorizar o valor ao cliente por meio de feedback contínuo e promover a colaboração da equipe é a",
    [
      "Scrum, por organizar o trabalho em sprints fixas, com foco em entregas incrementais de software e adaptações baseadas em revisões periódicas.",
      "Kanban, por utilizar um fluxo contínuo de trabalho, permitindo a entrega de funcionalidades conforme são concluídas, sem ciclos fechados de tempo.",
      "XP (Extreme Programming), por enfatizar práticas como programação em par, testes automatizados e integração contínua, visando adaptação rápida a mudanças.",
      "Waterfall (Cascata), por ser uma metodologia linear e estruturada, permitindo controle e planejamento durante as fases do projeto.",
      "Lean, por eliminar desperdícios e otimizar o uso de recursos em projetos complexos, buscando entregas mais eficientes.",
    ],
    0,
    "O enunciado pede ciclos incrementais, feedback contínuo e colaboração: é a descrição do Scrum. “Ciclos” elimina o Kanban, que é fluxo contínuo sem iterações fechadas; o XP responde pelas práticas técnicas, não pela estrutura de inspeção e adaptação.",
    "esp-agil",
  ),
  q(
    48,
    T,
    "Spring",
    "No desenvolvimento de software, os frameworks Spring, Spring Cloud, Spring Boot, Hibernate e JUnit desempenham papéis importantes na construção de aplicações modernas. Assinale a opção correta em relação às características e finalidades desses frameworks.",
    [
      "O Spring Boot é responsável por fornecer uma solução para desenvolvimento de microsserviços escaláveis, enquanto o Spring Cloud facilita a configuração e o gerenciamento de sistemas distribuídos.",
      "O Hibernate é um framework de teste para aplicações Java, amplamente utilizado em conjunto com o JUnit para realizar testes de unidade.",
      "O Spring é um framework voltado exclusivamente para o desenvolvimento de aplicações monolíticas, não oferecendo suporte para arquiteturas baseadas em microsserviços.",
      "O JUnit é um framework de persistência utilizado para o mapeamento objeto-relacional (ORM), permitindo interações eficientes com bancos de dados.",
      "O Spring Boot elimina a necessidade de configuração manual de dependências e servidores de aplicação, mas exige o uso de servidores como Tomcat e JBoss em modo standalone.",
    ],
    0,
    "Boot acelera a criação de serviços e Cloud fornece os recursos de sistemas distribuídos. As demais trocam os papéis: Hibernate é ORM (não teste), JUnit é teste (não ORM), Spring atende também microsserviços, e Boot embarca o servidor em vez de exigir um standalone.",
    "esp-plataformas",
  ),
  q(
    49,
    T,
    "Redes corporativas",
    "Uma empresa multinacional está implantando diferentes tipos de redes para melhorar a comunicação e o compartilhamento de informações entre seus funcionários, parceiros e clientes. Cada tipo de rede tem finalidades e características distintas, como o nível de acesso e o público-alvo.\nCom base nos conceitos de Internet, extranet, intranet e portal, assinale a opção que descreve corretamente o uso dessas redes em um ambiente corporativo.",
    [
      "A intranet é uma rede pública global que conecta milhões de computadores ao redor do mundo, permitindo a comunicação e o compartilhamento de informações sem restrições.",
      "A extranet permite que organizações compartilhem informações internamente, sendo acessível apenas por funcionários dentro da rede corporativa.",
      "O portal corporativo interno é uma página da web acessada publicamente, centralizando informações e serviços para usuários externos, como clientes e fornecedores.",
      "A Internet é uma rede restrita, acessível apenas a usuários autorizados, projetada para compartilhar informações dentro de uma organização.",
      "A extranet é uma rede que utiliza tecnologias da Internet para permitir o acesso controlado a informações e serviços de uma organização, tanto para usuários internos quanto para parceiros externos autorizados.",
    ],
    4,
    "A extranet estende recursos corporativos a parceiros com controle de acesso. As demais trocam as definições: (A) descreve a Internet chamando-a de intranet, (B) descreve a intranet chamando-a de extranet, (C) confunde portal interno com público e (D) descreve a intranet chamando-a de Internet.",
    "esp-arquitetura",
  ),
  q(
    50,
    T,
    "SPA e PWA",
    "Considerando as definições e características de SPA (Single Page Application) e PWA (Progressive Web Application), assinale a opção correta sobre suas principais diferenças e aplicações.",
    [
      "Ambas SPA e PWA dependem exclusivamente de frameworks JavaScript para funcionar, sendo que sem eles essas tecnologias não podem ser implementadas.",
      "Uma SPA carrega todas as interações do usuário em uma única página sem a necessidade de recarregar a página, enquanto uma PWA é projetada para funcionar como um site com funcionalidades nativas.",
      "O foco principal de uma PWA é fornecer uma experiência de página única similar a uma SPA, com o objetivo de evitar recarregamentos completos de página.",
      "SPAs requerem Service Workers para fornecer funcionalidades como cache e notificações, característica fundamental para seu funcionamento offline.",
      "Uma SPA depende exclusivamente de um navegador para ser executada, enquanto uma PWA pode ser instalada diretamente no sistema operacional do dispositivo como um aplicativo nativo.",
    ],
    1,
    "SPA troca o conteúdo sem recarregar a página; PWA é aplicação web com capacidades nativas. Service Worker é requisito de PWA, não de SPA, e o foco da PWA não é a experiência de página única.",
    "esp-arquitetura",
  ),
  q(
    51,
    T,
    "SOLID",
    "Em um projeto de software utilizando orientação a objetos, foi implementado o código em Java reproduzido no texto de apoio.\nCom base no princípio de Substituição de Liskov (L), que faz parte dos princípios SOLID, em relação à implementação do método emitirSom, assinale a opção correta.",
    [
      "A classe Cachorro não pode sobrescrever o método emitirSom, pois isso viola o princípio da Substituição de Liskov.",
      "O princípio da Substituição de Liskov é violado porque a classe Cachorro altera o comportamento do método emitirSom herdado de Animal.",
      "O código está de acordo com o princípio da Substituição de Liskov, já que a classe Cachorro pode ser usada no lugar da classe Animal sem comprometer a corretude do programa.",
      "O princípio da Substituição de Liskov exige que o método emitirSom de Cachorro seja exatamente igual ao de Animal.",
      "A implementação fere o princípio da Substituição de Liskov porque o método sobrescrito deve lançar uma exceção quando chamado.",
    ],
    2,
    "Sobrescrever é polimorfismo, o objetivo da herança — não viola LSP. O princípio só é ferido quando o subtipo quebra o contrato: lança exceção onde a base não lançava, fortalece pré-condições ou enfraquece pós-condições.",
    "esp-engenharia",
    `class Animal {
    void emitirSom() {
        System.out.println("Som genérico");
    }
}

class Cachorro extends Animal {
    @Override
    void emitirSom() {
        System.out.println("Latido");
    }
}`,
  ),
  q(
    52,
    T,
    "Desenvolvimento mobile",
    "No desenvolvimento de aplicativos móveis para Android e iOS, uma das abordagens mais comuns é o uso de frameworks que permitem o desenvolvimento multiplataforma, reduzindo o esforço de criação de código para cada sistema operacional. O framework popular para o desenvolvimento multiplataforma e que utiliza a linguagem Dart é chamado de",
    ["Xamarin.", "Flutter.", "React Native.", "Ionic.", "SwiftUI."],
    1,
    "Flutter, do Google, usa Dart. React Native usa JavaScript/TypeScript, Xamarin usa C#, Ionic usa HTML/CSS/JS e SwiftUI é nativo de iOS, com Swift.",
    "esp-plataformas",
  ),
  q(
    53,
    T,
    "Inteligência artificial",
    "A Inteligência Artificial (IA) é uma área da ciência da computação que visa desenvolver sistemas capazes de realizar tarefas que normalmente exigiriam inteligência humana.\nO conceito que está mais diretamente relacionado ao desenvolvimento de sistemas que aprendem com os dados e melhoram seu desempenho ao longo do tempo é o de",
    [
      "Algoritmo Genético.",
      "Redes Neurais Artificiais.",
      "Lógica Booleana.",
      "Busca Heurística.",
      "Programação Linear.",
    ],
    1,
    "Redes neurais ajustam pesos a partir de dados de treinamento — é a definição de aprendizado de máquina. Algoritmo genético é otimização evolutiva, e as demais não aprendem com dados.",
    "esp-plataformas",
  ),
  q(
    54,
    T,
    "HTTPS",
    "Em um ambiente corporativo, uma empresa de e-commerce precisa garantir a segurança das transações realizadas por seus clientes através de seu site. Para isso, o site utiliza o protocolo HTTPS, que combina o protocolo HTTP com uma camada adicional de segurança.\nAssinale a opção que apresenta a diferença entre os protocolos SSL e TLS no contexto de sua aplicação em comunicações seguras via HTTPS.",
    [
      "O SSL é mais seguro que o TLS, pois utiliza um algoritmo de criptografia mais avançado.",
      "O TLS substitui o SSL, corrigindo vulnerabilidades encontradas nas versões anteriores do SSL e implementando melhorias de segurança.",
      "O TLS e o SSL são intercambiáveis, pois ambos oferecem o mesmo nível de segurança, com a única diferença sendo a compatibilidade de alguns navegadores.",
      "O HTTPS só funciona com o protocolo SSL, pois foi o primeiro protocolo desenvolvido para essa finalidade.",
      "O SSL e o TLS são usados conjuntamente para garantir um nível de segurança adicional em transações bancárias, sendo o SSL utilizado para a autenticação e o TLS para a criptografia dos dados.",
    ],
    1,
    "TLS é o sucessor do SSL e corrigiu vulnerabilidades das versões antigas (POODLE, DROWN). SSL 2.0 e 3.0 estão obsoletos; HTTPS hoje roda sobre TLS, apesar de o termo “SSL” sobreviver por inércia.",
    "esp-seguranca",
  ),
  q(
    55,
    T,
    "Arquiteturas",
    "Em relação às arquiteturas hexagonal e de microsserviços, considere as seguintes afirmações:\nI. A arquitetura hexagonal, também chamada de Arquitetura de Portas e Adaptadores, visa separar a lógica de negócios das interfaces externas, permitindo uma fácil troca de implementações.\nII. Microsserviços são pequenos serviços que compartilham o mesmo banco de dados, promovendo maior acoplamento entre os módulos da aplicação para garantir a consistência dos dados.\nIII. A arquitetura monolítica pode ser distribuída, mas requer que todos os módulos sejam implantados como um conjunto, ao contrário dos microsserviços, que permitem a implantação independente de cada módulo.\n\nEstá correto o que se afirma em",
    [
      "I, apenas.",
      "II, apenas.",
      "III, apenas.",
      "I e II, apenas.",
      "I e III, apenas.",
    ],
    4,
    "I e III estão corretas. II é falsa: microsserviços têm banco próprio por serviço justamente para reduzir acoplamento — compartilhar banco é o antipadrão shared database.",
    "esp-arquitetura",
  ),
  q(
    56,
    T,
    "DevOps",
    "No contexto de DevOps, o conceito que descreve única e corretamente a prática de fornecer rapidamente uma nova versão de software ao ambiente de produção com o mínimo de interrupções para os usuários é chamado",
    [
      "Integração Contínua (CI).",
      "Entrega Contínua (CD).",
      "Gerenciamento de Configuração.",
      "Monitoramento Contínuo.",
      "Controle de Versão.",
    ],
    1,
    "Continuous Delivery mantém o software sempre pronto para produção e automatiza a disponibilização frequente e segura de versões. A CI para no build e nos testes: não entrega nada ao usuário.",
    "esp-engenharia",
  ),
  q(
    57,
    T,
    "Testes",
    "Em relação aos diferentes tipos de testes de software, considere as afirmativas abaixo:\nI. Os testes unitários focam em verificar o comportamento de unidades isoladas de código, como funções ou métodos, garantindo que funcionem conforme o esperado.\nII. Os testes de integração buscam verificar a interação entre diferentes módulos ou componentes do sistema, visando garantir que funcionem corretamente quando combinados.\nIII. O Test-Driven Development (TDD) segue a prática de escrever os testes antes do código funcional, incentivando a criação de código mais limpo e eficiente.\nIV. Os testes de usabilidade avaliam a experiência do usuário ao interagir com o software, verificando se a interface é intuitiva e eficiente.\n\nEstá correto o que se afirma em",
    [
      "I, II e IV, apenas.",
      "I, III e IV, apenas.",
      "II, III e IV, apenas.",
      "I, II, III e IV.",
      "I e III, apenas.",
    ],
    3,
    "As quatro afirmativas descrevem corretamente os respectivos conceitos: unidade isolada, interação entre módulos, ciclo Red-Green-Refactor do TDD e avaliação da experiência do usuário.",
    "esp-engenharia",
  ),
  q(
    58,
    T,
    "XML, XSLT e JSON",
    "Sobre as tecnologias XML, XSLT e JSON, assinale a opção correta.",
    [
      "O XML é mais eficiente que o JSON em termos de legibilidade e compactação de dados, sendo amplamente utilizado em aplicações web modernas devido à sua simplicidade.",
      "O XSLT é uma linguagem utilizada para transformar documentos JSON em outro formato, como HTML ou XML.",
      "O JSON é amplamente utilizado em APIs devido à sua estrutura simples e leve, que facilita o transporte de dados entre cliente e servidor.",
      "Tanto XML quanto JSON têm suporte nativo para transformação de dados utilizando XSLT, o que facilita sua manipulação em diferentes formatos.",
      "O XML e o JSON são formatos estritamente equivalentes em termos de expressividade e uso no armazenamento e transporte de dados em diferentes plataformas.",
    ],
    2,
    "JSON é leve e simples, o que o tornou padrão em APIs REST. XML é mais verboso que JSON; XSLT transforma XML, não JSON; e os dois formatos não são estritamente equivalentes.",
    "esp-arquitetura",
  ),
  q(
    59,
    T,
    "Sistemas de suporte à decisão",
    "Os Sistemas de Suporte à Decisão (SSDs) contribuem para gestores na tomada de decisões, utilizando dados, análises e algoritmos sofisticados. Eles auxiliam a enfrentar diferentes tipos de problemas, desde os muito bem definidos até os que exigem uma certa intuição e julgamento humano.\nAssinale a opção que representa corretamente a capacidade dos SSDs de lidar com diferentes tipos de problemas e decisões:",
    [
      "Os SSDs são adequados apenas para problemas estruturados, com procedimentos claramente definidos e automatizáveis.",
      "Os SSDs são ideais para problemas não estruturados, em que a intuição e o julgamento humano são fundamentais.",
      "Os SSDs são mais eficazes em problemas semiestruturados, combinando elementos estruturados e não estruturados.",
      "Os SSDs podem ser aplicados a problemas estruturados, semiestruturados e não estruturados, oferecendo flexibilidade para apoiar decisões em diversos contextos.",
      "Os SSDs são limitados a problemas específicos de uma única área funcional e não se aplicam a outros setores empresariais.",
    ],
    3,
    "SSDs combinam dados, modelos e julgamento humano, e a flexibilidade é sua característica definidora. O próprio enunciado indica o espectro “desde os muito bem definidos até os que exigem intuição”, o que elimina as alternativas restritivas.",
    "esp-dados",
  ),
  q(
    60,
    T,
    "Data Warehouse",
    "Em arquiteturas modernas de Data Warehousing, o processo de ETL é fundamental para preparar os dados de forma eficiente para a tomada de decisões estratégicas.\nEle é como uma ponte entre os sistemas e o Data Warehouse.\nNesse contexto, o principal objetivo do processo de ETL em uma solução de Data Warehousing é",
    [
      "criar visualizações e dashboards interativos para serem analisados em tempo real.",
      "realizar análises estatísticas complexas nos dados, aplicando técnicas de modelagem preditiva para descobrir insights ocultos.",
      "desenvolver e treinar modelos de machine learning, facilitando a previsão de tendências.",
      "extrair dados de diversas fontes, transformá-los em um formato padronizado e consistente e carregá-los no Data Warehouse.",
      "gerenciar o acesso e a segurança dos dados armazenados no Data Warehouse, garantindo assim que as informações estejam protegidas contra acessos não autorizados.",
    ],
    3,
    "É a própria definição da sigla: Extract, Transform, Load. Dashboards, estatística e machine learning vêm depois, sobre os dados já integrados.",
    "esp-dados",
  ),
  q(
    61,
    T,
    "BI e qualidade de dados",
    "Na hora de colocar um projeto de BI em prática, mapear as fontes de dados é primordial. É como preparar o terreno antes de construir: se a base não for sólida, a casa não fica em pé. É necessário garantir que as informações que vamos usar sejam úteis, relevantes e de alta qualidade. Nessa fase, seguir as boas práticas é fundamental para que os dados se encaixem nas necessidades do negócio e nos objetivos do projeto. Mas cuidado! Algumas abordagens podem acabar prejudicando tudo se não forem bem executadas.\nAssinale a opção que descreve uma prática **não recomendada** no mapeamento de fontes de dados para um projeto de BI.",
    [
      "Conduzir entrevistas abrangentes com usuários e stakeholders, utilizando técnicas de elicitação para extrair requisitos detalhados e garantir que todas as necessidades sejam consideradas.",
      "Analisar documentos e sistemas existentes para identificar potenciais fontes de dados, assegurando que todo o repositório de informações relevantes seja considerado.",
      "Coletar dados de todas as fontes disponíveis, sem discriminação, incluindo aqueles que apresentam inconsistências, incertezas ou baixa relevância, a fim de maximizar a quantidade de dados no sistema.",
      "Avaliar a qualidade dos dados e sua adequação aos objetivos do projeto, garantindo que apenas informações precisas e confiáveis sejam utilizadas para gerar insights de valor.",
      "Manter uma documentação detalhada das fontes de dados, incluindo suas características, formatos e relacionamentos, para garantir uma governança de dados eficaz e facilitar auditorias futuras.",
    ],
    2,
    "Coletar tudo sem discriminação é garbage in, garbage out: aumenta custo, ruído e risco de decisão errada. As demais são boas práticas de mapeamento de fontes.",
    "esp-dados",
  ),
  q(
    62,
    T,
    "OWASP",
    "A OWASP Top 10 é uma lista amplamente reconhecida das vulnerabilidades mais críticas em aplicações web, criada pela Open Web Application Security Project (OWASP). Atualizada periodicamente, a lista destaca as principais falhas de segurança que podem ser exploradas por atacantes. Com foco em orientar desenvolvedores e equipes de segurança, a OWASP Top 10 serve como uma referência essencial para proteger aplicações web e melhorar as práticas de desenvolvimento seguro.\nEm sua versão OWASP Top 10:2021, identificamos como uma categoria de vulnerabilidade",
    [
      "a falsificação de solicitação do lado do servidor.",
      "a proteção da cadeia de suprimentos de software.",
      "a proteção do ambiente de engenharia.",
      "o treinamento operacional.",
      "o uso de recursos de linguagens e frameworks.",
    ],
    0,
    "Falsificação de solicitação do lado do servidor é o SSRF (Server-Side Request Forgery), categoria A10 da lista de 2021. As demais soam plausíveis, mas pertencem a outros frameworks, não ao Top 10.",
    "esp-seguranca",
  ),
  q(
    63,
    T,
    "Segurança X.800",
    "A arquitetura de segurança X.800 para o modelo OSI define mecanismos de segurança próprios, que podem ser incorporados à uma camada de protocolo específica com o objetivo de oferecer serviços de segurança OSI, ou mecanismos de segurança disseminados, que não são específicos de uma camada ou serviço.\nAssinale a opção que indica um mecanismo de segurança específico.",
    [
      "Detecção de evento.",
      "Funcionalidade confiável.",
      "Preenchimento de tráfego.",
      "Rótulo de segurança.",
      "Trilha de auditoria de segurança.",
    ],
    2,
    "Preenchimento de tráfego (traffic padding) é mecanismo específico, usado contra análise de tráfego. Detecção de evento, funcionalidade confiável, rótulo de segurança e trilha de auditoria são mecanismos disseminados.",
    "esp-seguranca",
  ),
  q(
    64,
    T,
    "Controle de acesso",
    "As políticas de controle de acesso em sistemas computacionais são fundamentais para garantir a segurança e a integridade dos dados, regulando quem pode acessar, modificar ou interagir com recursos específicos.\nA política de controle de acesso cujo procedimento baseia-se na comparação de rótulos de segurança com autorizações que indicam quais entidades do sistema têm direito a acessar determinados recursos é a de controle de acesso",
    [
      "discricionário.",
      "mandatório.",
      "por entrada confiável.",
      "por papéis.",
      "por privilégio mínimo.",
    ],
    1,
    "Rótulo de segurança comparado a autorização (clearance) é a mecânica do controle mandatório (MAC), aplicado pelo sistema segundo política central. No discricionário quem concede é o dono do recurso; privilégio mínimo é princípio, não política.",
    "esp-seguranca",
  ),
  q(
    65,
    T,
    "ETL e ELT",
    "Sobre as técnicas de integração e ingestão de dados ETL (Extract, Transform, Load) e ELT (Extract, Load, Transform), assinale a opção **incorreta**.",
    [
      "Em ETL, os dados são transformados antes de serem carregados no sistema de destino.",
      "ETL é mais adequado para sistemas de data warehouse tradicionais, onde a transformação de dados ocorre antes do carregamento.",
      "ELT aproveita a capacidade de processamento do sistema de destino, transformando os dados após o carregamento.",
      "ELT é mais eficiente em cenários onde o volume de dados é pequeno e o processamento pode ser feito fora do sistema de destino.",
      "ETL pode ser mais lento em comparação ao ELT quando o sistema de destino tem alta capacidade de processamento.",
    ],
    3,
    "A alternativa inverte o cenário: ELT é vantajoso com grandes volumes e transformação DENTRO do destino. Volume pequeno com processamento fora do destino descreve o ETL.",
    "esp-dados",
  ),
  q(
    66,
    T,
    "NoSQL",
    "Sobre bancos de dados NoSQL, assinale a opção correta.",
    [
      "Bancos de dados NoSQL seguem estritamente as propriedades ACID.",
      "Os bancos de dados NoSQL utilizam sempre o modelo relacional de dados.",
      "Bancos de dados NoSQL são adequados para sistemas que exigem alta disponibilidade e escalabilidade horizontal.",
      "Em um banco de dados NoSQL, os dados são sempre armazenados em forma de grafos.",
      "Bancos de dados NoSQL são melhores para sistemas como ERPs e CRMs.",
    ],
    2,
    "NoSQL atende bem sistemas distribuídos que exigem disponibilidade e escala horizontal, adotando em geral BASE em vez de ACID estrito. Ele não usa modelo relacional, não armazena sempre grafos, e ERP/CRM pedem integridade transacional forte, terreno do relacional.",
    "esp-dados",
  ),
  q(
    67,
    T,
    "OLAP e modelagem dimensional",
    "Sobre as diferenças entre abordagens relacionais e multidimensionais em bancos de dados, assinale a opção correta.",
    [
      "A abordagem multidimensional é mais eficiente para transações online (OLTP) do que a abordagem relacional.",
      "A abordagem relacional é usada principalmente em sistemas de apoio à decisão (OLAP), enquanto a multidimensional é usada em sistemas transacionais (OLTP).",
      "A abordagem multidimensional facilita a análise de grandes volumes de dados organizados em dimensões e métricas.",
      "Em uma abordagem relacional, os dados são organizados em cubos, o que facilita a análise em tempo real.",
      "A abordagem multidimensional não suporta agregações de dados ou cálculos como somas e médias.",
    ],
    2,
    "Dimensões, métricas e agregações são a base do OLAP. Cubo é conceito multidimensional, não relacional; e o multidimensional é justamente excelente em agregações — (E) inverte o fato.",
    "esp-dados",
  ),
  q(
    68,
    T,
    "Scrum Master",
    "Uma equipe de desenvolvimento está trabalhando em um projeto importante usando Scrum. Durante o Daily Scrum, um dos desenvolvedores comenta que está com dificuldades para concluir uma tarefa e provavelmente não conseguirá terminá-la até o fim do Sprint. Diante disso, o Scrum Master sugere que a equipe pense em como reorganizar as tarefas para garantir que o objetivo do Sprint ainda seja alcançado.\nPara ajudar a equipe a continuar no caminho certo, o Scrum Master deve",
    [
      "redistribuir as tarefas por conta própria, sem envolver a equipe, para garantir que tudo seja concluído a tempo.",
      "incentivar a equipe a discutir o problema e encontrar uma solução colaborativa, removendo qualquer obstáculo, mas sem interferir demais.",
      "assumir a tarefa do desenvolvedor, garantindo que o prazo seja cumprido.",
      "escalar o problema ao Product Owner, deixando que ele reorganize as prioridades e tarefas.",
      "encerrar o Sprint mais cedo, já que a tarefa não será concluída.",
    ],
    1,
    "O time é auto-gerenciável: cabe ao Scrum Master facilitar a discussão e remover impedimentos, não decidir pela equipe, assumir tarefas nem encerrar o Sprint.",
    "esp-agil",
  ),
  q(
    69,
    T,
    "Gestão híbrida",
    "No contexto do gerenciamento de projetos, uma abordagem Ágil Híbrida é caracterizada por",
    [
      "utilizar exclusivamente metodologias ágeis em todos os aspectos do projeto.",
      "combinar práticas ágeis com métodos tradicionais de gerenciamento de projetos para atender às necessidades específicas da equipe e do projeto.",
      "adotar apenas as cerimônias do Scrum, sem considerar outros métodos.",
      "implementar um plano fixo e detalhado antes de iniciar o projeto, sem revisões.",
      "focar unicamente na documentação, ignorando a interação com a equipe.",
    ],
    1,
    "Híbrido é justamente a combinação: governança e marcos em cascata com execução iterativa, conforme a necessidade do projeto e da equipe.",
    "esp-agil",
  ),
  q(
    70,
    T,
    "Planejamento de Sprint",
    "A equipe de marketing resolveu mudar as coisas nessa eleição e escolheu usar o SCRUM. Na reunião de planejamento do Sprint, o coordenador de campanha (Product Owner) apresentou uma lista de tarefas essenciais: criar conteúdo para as redes sociais, produzir vídeos e organizar eventos locais. Um dos membros da equipe sugeriu que todas as tarefas fossem incluídas no Sprint, mas, dada a complexidade, não devem caber dentro do Sprint.\nAssinale a opção que indica como a equipe de marketing deveria lidar com a seleção das tarefas para o Sprint.",
    [
      "O membro da equipe está certo em querer incluir todas as tarefas, já que campanhas eleitorais são imprevisíveis e mudanças de última hora podem acontecer.",
      "A equipe deve priorizar as tarefas que podem ser concluídas dentro do Sprint, levando em conta a capacidade de trabalho e o tempo disponível, para garantir que os objetivos mais importantes da campanha sejam alcançados.",
      "O coordenador de campanha (Product Owner) deve decidir sozinho quais tarefas serão incluídas no Sprint, sem consultar o restante da equipe.",
      "A equipe deve colocar o máximo de tarefas possível no Sprint para cobrir todas as frentes da campanha, mesmo que algumas não sejam finalizadas.",
      "O Scrum Master deve adicionar mais tarefas ao Sprint durante o processo, se perceber que a equipe está avançando rápido demais.",
    ],
    1,
    "O Sprint deve respeitar a capacidade do time e concentrar-se na Meta. O PO prioriza o backlog, mas quem dimensiona o que cabe são os Developers — e não se empurram itens novos no meio da Sprint.",
    "esp-agil",
  ),
];

// Gabarito oficial FGV - ATI Desenvolvimento de Software, PROVA TIPO 4 (AZUL),
// aplicada em 17/11/2024. Este é o caderno de onde as 70 questões foram transcritas.
// As respostas ficam declaradas em cada questão acima; o bloco abaixo apenas CONFERE
// que elas continuam batendo com o gabarito oficial — nunca as sobrescreve.
const officialAnswerLetters =
  "EACDDCACEDDABEBDECBE BCDADBBACCABCEDBECDA DCBABAAAEBCBBBEBDCDD CACBDCCBBB"
    .replace(/\s+/g, "")
    .split("");

questionsData.forEach((question, index) => {
  const answerLetter = officialAnswerLetters[index];
  if (!answerLetter) return;
  const expected = answerLetter.charCodeAt(0) - "A".charCodeAt(0);
  if (question.correctAnswer !== expected) {
    console.error(
      `[gabarito] Questão ${question.id}: marcada ${String.fromCharCode(65 + question.correctAnswer)}, ` +
        `oficial Tipo 4 é ${answerLetter}.`,
    );
  }
});
